### ISSUE TITLE
dumbo cat leads to unsupported operand +: Options and list

### ISSUE THREAD

**Issue by mokele** [klbostee/dumbo#54]
This is presumably due to the options refactoring, since this works in 0.21.31

`Traceback (most recent call last):
  File "/usr/local/bin/dumbo", line 9, in <module>
    load_entry_point('dumbo==0.21.32', 'console_scripts', 'dumbo')()
  File "/usr/local/lib/python2.6/dist-packages/dumbo-0.21.32-py2.6.egg/dumbo/__init__.py", line 32, in execute_and_exit    sys.exit(dumbo())
  File "/usr/local/lib/python2.6/dist-packages/dumbo-0.21.32-py2.6.egg/dumbo/cmd.py", line 42, in dumbo    retval = cat(sys.argv[2], parseargs(sys.argv[2:]))
  File "/usr/local/lib/python2.6/dist-packages/dumbo-0.21.32-py2.6.egg/dumbo/cmd.py", line 101, in cat    return create_filesystem(opts).cat(path, opts)
  File "/usr/local/lib/python2.6/dist-packages/dumbo-0.21.32-py2.6.egg/dumbo/backends/unix.py", line 114, in cat
    return decodepipe(opts + [('file', path)]) 
TypeError: unsupported operand type(s) for +: 'Options' and 'list'`

**Comment by klbostee** [comment]
Fixored. Thanks Steve!
